### ISSUE TITLE
When I include vue-moment.min.js I get a error 

### ISSUE THREAD

**Issue by raducretu** [brockpetrie/vue-moment#27] opened 2017-02-14 14:16 UTC
Hi there,

I keep getting this error when I add vue-moment.min.js to the page:
Global Code — vue-moment.min.js:1 ReferenceError: Can't find variable: require

moment.js and vue.js are loaded before. Any idea?

Thanks

**Comment by brockpetrie** [comment] 2017-03-21 16:24
This is a duplicate of #11, so closing this one.

**Closed by brockpetrie** 2017-03-21 16:24 UTC
