### ISSUE TITLE
IE script errors with version > 4.*

### ISSUE THREAD

**Issue by SayedShahidi** [brockpetrie/vue-moment#85] opened 2018-06-07 07:18 UTC
Internet explorer is giving script errors. I am assuming that the code is not being transpiled the right way. In my case i fixed the issue by going back to version 3.2.0 where it works and functions normally.

**Comment by dirknilius** [comment] 2018-06-10 19:35
Confirmed. The problem is that the package isn't transpiled nor polyfilled at all :( So it cannot be used with any IE version.

**Comment by SayedShahidi** [comment] 2018-06-12 07:15
@rosdi 
Ok, that is strange, anyways checkout the screenshot for the line number and method. The line number may differ since this is the build version.

![screen shot 2018-06-06 at 12 41 00](https://user-images.githubusercontent.com/11387347/41275178-5863f940-6e20-11e8-8e8d-dfbd9c9021b2.png)

**Comment by rosdi** [comment] 2018-06-12 11:09
Oh well... I am using it directly in browser.. I just copied the code as is and it works in IE11. So i guess the culprit is not in the component itself?

**Comment by dirknilius** [comment] 2018-06-12 15:48
@rosdi Looks like you took the version from master branch. This works and the transpiler produces nearly the same. But we talking about the 4.0.0 version / branch. Try to transpile it and it will work. Also you get a complete different version.

**Comment by rosdi** [comment] 2018-06-12 16:52
Ah!.. I saw the npm package is 4.0.0 and I wrongly assume it is from master branch... that explains why the transpiled code is nearly identical... my bad... 

Sure enough... a quick glance at 4.0.0 branch indicates it wont work in IE11 without transpiling... so there is no intention to transpile it to es5 and support IE11?

**Comment by BrockReece** [comment] 2018-06-13 07:49
Hi everyone, thanks for pointing this out.

I don't think this was intentional, we just need to look at how we are transpilng our code.

@brockpetrie what would you think to using something like [Bili](https://bili.egoist.moe/#/) to build our browser friendly dist file, this is probably something we could automate through Travis when tagging?

**Comment by rosdi** [comment] 2018-06-20 08:12
Awesome!.. hopefully this can be merged into 4.0.0... at the moment I copied the code and remove unnecessary stuff manually so that I can use it in browser directly.

**Closed** 2018-06-21 17:41 UTC
